
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'A893E8CC439401119FABDAD7B327C382'
    
_lr_action_items = {'LPAREN':([0,3,6,8,9,10,12,14,15,16,21,29,31,],[3,3,3,3,3,3,21,23,23,23,23,21,23,]),'OR':([1,2,4,5,7,11,12,13,17,18,19,20,22,24,25,26,32,],[10,-8,-6,-5,15,10,-8,-4,-3,10,-2,-7,-13,-9,-10,-11,-12,]),'EQUALS':([2,7,12,32,],[-13,14,-13,-12,]),'FALSE':([0,3,6,8,9,10,],[5,5,5,5,5,5,]),'SYMBOL':([0,3,6,8,9,10,14,15,16,21,23,31,],[2,12,2,2,2,2,22,22,22,22,29,22,]),'$end':([1,2,4,5,13,17,18,19,20,22,24,25,26,32,],[0,-8,-6,-5,-4,-3,-1,-2,-7,-13,-9,-10,-11,-12,]),'RPAREN':([2,4,5,11,12,13,17,18,19,20,22,24,25,26,27,28,30,32,33,],[-8,-6,-5,20,-8,-4,-3,-1,-2,-7,-13,-9,-10,-11,30,-15,32,-12,-14,]),'TRUE':([0,3,6,8,9,10,],[4,4,4,4,4,4,]),'IMPLIES':([1,2,4,5,11,12,13,17,18,19,20,22,24,25,26,32,],[9,-8,-6,-5,9,-8,-4,-3,9,-2,-7,-13,-9,-10,-11,-12,]),'COMMA':([22,28,32,],[-13,31,-12,]),'AND':([1,2,4,5,7,11,12,13,17,18,19,20,22,24,25,26,32,],[8,-8,-6,-5,16,8,-8,-4,-3,8,8,-7,-13,-9,-10,-11,-12,]),'NOT':([0,3,6,8,9,10,],[6,6,6,6,6,6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'FORMULA':([0,3,6,8,9,10,],[1,11,13,17,18,19,]),'TERMLIST':([21,31,],[27,33,]),'TERM':([0,3,6,8,9,10,14,15,16,21,31,],[7,7,7,7,7,7,24,25,26,28,28,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> FORMULA","S'",1,None,None,None),
  ('FORMULA -> FORMULA IMPLIES FORMULA','FORMULA',3,'p_formula_binary','PLY.py',45),
  ('FORMULA -> FORMULA OR FORMULA','FORMULA',3,'p_formula_binary','PLY.py',46),
  ('FORMULA -> FORMULA AND FORMULA','FORMULA',3,'p_formula_binary','PLY.py',47),
  ('FORMULA -> NOT FORMULA','FORMULA',2,'p_formula_not','PLY.py',51),
  ('FORMULA -> FALSE','FORMULA',1,'p_formula_boolean','PLY.py',55),
  ('FORMULA -> TRUE','FORMULA',1,'p_formula_boolean','PLY.py',56),
  ('FORMULA -> LPAREN FORMULA RPAREN','FORMULA',3,'p_formula_group','PLY.py',60),
  ('FORMULA -> SYMBOL','FORMULA',1,'p_formula_symbol','PLY.py',64),
  ('FORMULA -> TERM EQUALS TERM','FORMULA',3,'p_formula_equals','PLY.py',68),
  ('FORMULA -> TERM OR TERM','FORMULA',3,'p_formula_or','PLY.py',72),
  ('FORMULA -> TERM AND TERM','FORMULA',3,'p_formula_and','PLY.py',76),
  ('TERM -> LPAREN SYMBOL LPAREN TERMLIST RPAREN RPAREN','TERM',6,'p_term','PLY.py',80),
  ('TERM -> SYMBOL','TERM',1,'p_term','PLY.py',81),
  ('TERMLIST -> TERM COMMA TERMLIST','TERMLIST',3,'p_termlist','PLY.py',85),
  ('TERMLIST -> TERM','TERMLIST',1,'p_termlist','PLY.py',86),
]
